### PR TITLE
Qh 57

### PR DESCRIPTION
**Pull request by jasonlwj**

### CODE REVIEW

**Comment by jasonlwj** [comment]
Thoughts on changing the font colour of the new line? Or should we leave it as it is?

**Comment by ChrisNeedham24** [comment]
Wow, it's really impressive that you managed to do this changing only one file! 🔥

**Comment by ChrisNeedham24** [comment]
> Thoughts on changing the font colour of the new line? Or should we leave it as it is?

Yeah I reckon it would look nice as a different colour, plus in italics too I think. Not sure what colour personally, but probably something that fits with the general colour scheme. I was thinking that you could maybe colour-code them based on the percentage of players that have achieved it (sort of like a difficulty thing), but yeah we don't really need that if you don't want to do it.

**Comment by jasonlwj** [comment]
> > Thoughts on changing the font colour of the new line? Or should we leave it as it is?
> 
> Yeah I reckon it would look nice as a different colour, plus in italics too I think. Not sure what colour personally, but probably something that fits with the general colour scheme. I was thinking that you could maybe colour-code them based on the percentage of players that have achieved it (sort of like a difficulty thing), but yeah we don't really need that if you don't want to do it.

I am so doing that

**Comment by jasonlwj** [comment]
Changed the text colour to a subtle `darkgrey`. For rare achievements with under 10% player attainment, it becomes `orange` (though it looks more like a gold to my eyes).

**Pull request merged**
